import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { metricsCatalog, CATEGORIES } from '../src/metrics/index.js';
import type { Category } from '../src/metrics/index.js';

const CATEGORY_LABELS: Record<Category, string> = {
  documentation: 'Documentation',
  architecture: 'Architecture',
  testing: 'Testing',
  'automation-guardrails': 'Automation Guard Rails',
  'ai-context': 'AI Context',
  maintainability: 'Maintainability',
};

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function generate(): string {
  const lines: string[] = [];

  lines.push('# Metrics Reference');
  lines.push('');
  lines.push(
    'Generated from the metric catalog (`src/metrics/*.ts`) by `npm run docs:metrics`. Do not edit this file by hand — changes will be overwritten on the next generation run.',
  );
  lines.push('');
  lines.push('| Category | Metric | Points | Description | Instruction | Remediation |');
  lines.push('| --- | --- | --- | --- | --- | --- |');

  for (const category of CATEGORIES) {
    const metrics = metricsCatalog
      .filter((m) => m.category === category)
      .sort((a, b) => a.id.localeCompare(b.id));

    for (const m of metrics) {
      lines.push(
        `| ${CATEGORY_LABELS[category]} | \`${m.id}\` | ${m.points} | ${escapeCell(m.description)} | ${escapeCell(m.instruction)} | ${escapeCell(m.remediation)} |`,
      );
    }
  }

  lines.push('');
  return lines.join('\n');
}

const outputPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'docs',
  'METRICS.md',
);
writeFileSync(outputPath, generate());
console.log(`Wrote ${metricsCatalog.length} metrics to ${outputPath}`);
